on:
  push:
    branches:
      - master
      - main
      - default
  pull_request:
    branches:
      - '**'

name: Typecheck
jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm install
      - name: Typecheck ipfs-core-utils
        uses: gozala/typescript-error-reporter-action@v1.0.4
        with:
          project: packages/ipfs-core-utils
      - name: Generate typedefs for ipfs-core-utils
        run: npm run build:types --scope={ipfs-core-utils}
      - name: Typecheck ipfs-core
        uses: gozala/typescript-error-reporter-action@v1.0.4
        with:
          project: packages/ipfs-core
      - name: Generate typedefs for ipfs-core
        run: npm run build:types --scope={ipfs-core}
      - name: Typecheck ipfs-http-client
        uses: gozala/typescript-error-reporter-action@v1.0.4
        with:
          project: packages/ipfs-http-client
      - name: Typecheck ipfs
        uses: gozala/typescript-error-reporter-action@v1.0.4
        with:
          project: packages/ipfs
